/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-09-21 at 15:56:49 UTC 
 * Modify at your own risk.
 */

package com.appspot.englishsharing_1041.helloworld.model;

/**
 * Model definition for HelloQuestionRequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the helloworld. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class HelloQuestionRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String author;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String hint;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String original;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String question;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long verb;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAuthor() {
    return author;
  }

  /**
   * @param author author or {@code null} for none
   */
  public HelloQuestionRequest setAuthor(java.lang.String author) {
    this.author = author;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHint() {
    return hint;
  }

  /**
   * @param hint hint or {@code null} for none
   */
  public HelloQuestionRequest setHint(java.lang.String hint) {
    this.hint = hint;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOriginal() {
    return original;
  }

  /**
   * @param original original or {@code null} for none
   */
  public HelloQuestionRequest setOriginal(java.lang.String original) {
    this.original = original;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQuestion() {
    return question;
  }

  /**
   * @param question question or {@code null} for none
   */
  public HelloQuestionRequest setQuestion(java.lang.String question) {
    this.question = question;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVerb() {
    return verb;
  }

  /**
   * @param verb verb or {@code null} for none
   */
  public HelloQuestionRequest setVerb(java.lang.Long verb) {
    this.verb = verb;
    return this;
  }

  @Override
  public HelloQuestionRequest set(String fieldName, Object value) {
    return (HelloQuestionRequest) super.set(fieldName, value);
  }

  @Override
  public HelloQuestionRequest clone() {
    return (HelloQuestionRequest) super.clone();
  }

}
